[package]
name = "celeste-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
image = "0.25.6"
png = "0.17.16"

[dev-dependencies]
rstest = "0.25.0"
rstest_reuse = "0.7.0"
